name: ent_clinic
description: "A Flutter-based clinic management system for ENT clinics."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.0.5
  datetime_picker_formfield: ^2.0.1
  adaptive_theme: ^3.6.0
  expansion_tile_card: ^3.0.0
  fl_chart: ^0.67.0
  d_chart: ^2.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    # Readex Pro Font
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro.ttf